### ISSUE TITLE
Accelerate workflow by including SMOKE_RUN

### ISSUE THREAD

**Issue by patel-zeel** [probml/pyprobml#783] opened 2022-04-30 13:02 UTC
After adding D2L notebooks, workflow execution time has increased from 1 hour to 2 hours 14 minutes. Ideally, the workflow should be as fast as possible so that we can know the failing components quickly. One of the solutions for this is to enable an environment variable called SMOKE_RUN for notebooks containing epoch-wise training with a logic that if SMOKE_RUN is in the environment we run only 1-2 epochs else we run the maximum epochs as mentioned in the notebook.

**Comment by nalzok** [comment] 2022-04-30 14:51
Since the tests have no dependency on each other, running all tests in parallel could be another viable option to accelerate the workflow. There are multiple ways to do this: generate a workflow for each notebook from some template, use [`pytest-split`](https://blog.jerrycodes.com/pytest-split-and-github-actions/), or use [`strategy.matrix`](https://hanxiao.io/2021/01/24/Speedup-CI-Workflow-in-Github-Actions-via-Strategy-Matrix/#building-job-matrix-for-parallelization).

The execution time can be further reduced if you add some [cache](https://github.com/actions/cache) so that the dependencies don't need to be installed each time.

**Comment by patel-zeel** [comment] 2022-04-30 20:20
@nalzok These all are excellent suggestions! Would you like to work on a PR to do this?

**Comment by nalzok** [comment] 2022-04-30 20:46
Sure, I’ll do some experiments to figure out which one works best and create a PR. It might take a few days though, since it’s the midterm week!

**Comment by patel-zeel** [comment] 2022-05-06 06:58
@nalzok I think the parallel workflow has improved the runtime a lot however, we can still improve it with SMOKE_RUN wherever possible. We can export the time taken to run a notebook along with the log on [this dashboard](https://github.com/probml/pyprobml/blob/workflow_testing_indicator/README.md). It will help us decide if a notebook needs to be fastened using SMOKE_RUN.

**Comment by nalzok** [comment] 2022-05-06 07:11
Yeah, it’s always better to have more transparency! Another thing I want to mention is that we can probably cache the datasets from TFDS and PyTorch-vision, since downloading mega bytes of data from the Internet is going to be slow.

**Comment by patel-zeel** [comment] 2022-05-06 07:46
@nalzok Yes, caching the datasets is a good idea. Is it possible in GitHub Actions? If not, we can try to maintain our own container with pre-downloaded datasets and a pre-configured Python version.

**Comment by nalzok** [comment] 2022-05-06 15:15
I think it’s possible with GitHub Actions. I will investigate into that later.

**Comment by patel-zeel** [comment] 2022-05-11 10:04
@nalzok I think the latest modification time first approach is not working as expected in the workflow. From the initial checkup, I could see that the latest updated notebook (rf_feature_importance_mnist) did not have the largest time-stamp.
```
1651681026 notebooks/book1/18/dtree_sensitivity.ipynb
1651772231 notebooks/book1/18/fig_18_4.ipynb
1650191314 notebooks/book1/18/hinge_loss_plot.ipynb
1651681026 notebooks/book1/18/regtreeSurfaceDemo.ipynb
1651681026 notebooks/book1/18/rf_demo_2d.ipynb
1651681026 notebooks/book1/18/rf_feature_importance_mnist.ipynb
1651681026 notebooks/book1/18/spam_tree_ensemble_compare.ipynb
1651681026 notebooks/book1/18/spam_tree_ensemble_interpret.ipynb
1651772295 notebooks/book1/19/finetune_cnn_jax.ipynb
1651681026 notebooks/book1/19/finetune_cnn_torch.ipynb
1651301124 notebooks/book1/19/hbayes_maml.ipynb
1651772295 notebooks/book1/19/image_augmentation_jax.ipynb
1651681026 notebooks/book1/19/image_augmentation_torch.ipynb
1651774806 notebooks/book1/20/ae_mnist_conv.ipynb
1651681026 notebooks/book1/20/ae_mnist_tf.ipynb
```

**Comment by nalzok** [comment] 2022-05-11 16:06
I cannot reproduce the problem in my local git repository. Did you switch to the master branch and did a `git pull`?

```
$ git ls-files 'notebooks/book1/18/**.ipynb' -z | xargs -0 -n1 -I{} -- git log -1 --format='%at {}' {}
1651681026 notebooks/book1/18/bagging_trees.ipynb
1651681026 notebooks/book1/18/boosted_regr_trees.ipynb
1651681026 notebooks/book1/18/dtree_sensitivity.ipynb
1651772231 notebooks/book1/18/fig_18_4.ipynb
1650191314 notebooks/book1/18/hinge_loss_plot.ipynb
1651681026 notebooks/book1/18/regtreeSurfaceDemo.ipynb
1651681026 notebooks/book1/18/rf_demo_2d.ipynb
1652116108 notebooks/book1/18/rf_feature_importance_mnist.ipynb
1651681026 notebooks/book1/18/spam_tree_ensemble_compare.ipynb
1651681026 notebooks/book1/18/spam_tree_ensemble_interpret.ipynb
```

**Comment by patel-zeel** [comment] 2022-05-11 17:28
I tried cloning the original repo and got the same time stamps for all files

```
1652256012 notebooks/book1/21/hclust_yeast_demo.ipynb
1652256012 notebooks/book1/21/kmeans_minibatch.ipynb
1652256012 notebooks/book1/21/kmeans_silhouette.ipynb
1652256012 notebooks/book1/21/kmeans_voronoi.ipynb
1652256012 notebooks/book1/21/kmeans_yeast_demo.ipynb
1652256012 notebooks/book1/21/spectral_clustering_demo.ipynb
1652256012 notebooks/book1/21/vqDemo.ipynb
1652256012 notebooks/book1/21/yeast_data_viz.ipynb
1652256012 notebooks/book1/22/matrix_factorization_recommender.ipynb
1652256012 notebooks/book2/17/combining_kernels_by_multiplication.ipynb
1652256012 notebooks/book2/17/combining_kernels_by_summation.ipynb
1652256012 notebooks/book2/17/gprDemoArd.ipynb
1652256012 notebooks/book2/17/gprDemoNoiseFreeAndNoisy.ipynb
1652256012 notebooks/book2/20/LVAE.ipynb
```

I see that the first notebook executed by runner 0 on `master` is `notebooks/book2/20/LVAE.ipynb`. That is strange right? Ideally, it should be `notebooks/book1/18/rf_feature_importance_mnist.ipynb`.

**Comment by nalzok** [comment] 2022-05-12 00:49
Ah I can see the problem now. Just pushed a [commit](https://github.com/probml/pyprobml/commit/17e6a1035584db7706d9cbc894beafa3fdba8a49) to resolve the issue. Now the first notebook to be checked is `notebooks/book1/03/gauss_plot_2d.ipynb`, which makes sense since that's the notebook touched by the previous commit.

By default `actions/checkout@v3` does a shallow clone fetching only the latest commit, so all files have the same modification time. By setting `fetch-depth: 0` I instruct it to fetch the whole git commit history. Alternatively, we could also set something like `fetch-depth: 5` if we only want to prioritize testing the notebooks touched by the latest 5 commits.

**Comment by patel-zeel** [comment] 2022-05-12 04:03
That's great, @nalzok. It works as expected now!

**Comment by patel-zeel** [comment] 2022-05-12 04:09
@nalzok I was thinking if we should have a separate step to check the latest modified notebook to easily find out the problems with it. So, the new workflow can be: 1) code format 2) static import check 3) latest modified notebook check 4) all notebooks check and 5) combine & push the results. WDYT?

**Comment by nalzok** [comment] 2022-05-12 05:18
Makes sense to me. I have created a PR to implement the new stage: https://github.com/probml/pyprobml/pull/820

**Comment by murphyk** [comment] 2022-07-13 06:39
closing this seems to be fixed

**Closed by murphyk** 2022-07-13 06:39 UTC
Labels: internal
